### PR TITLE
Adding vite-preact

### PR DESCRIPTION
**Pull request by richajak**
### Checklist

- [ ] Title as described.
- [ ] Make sure you put things in the right category.
- [ ] The description of your item should be a sentence with less than 24 words.
- [ ] Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
- [ ] Always add your items to the end of a list.

### Plugins/Tools

- [x] The plugin/tool is working with **Vite 2.0 and onward**.
- [x] The project is Open Source.
- [ ] The project follows the [Vite Plugins Conventions](https://vitejs.dev/guide/api-plugin.html#conventions).
- [ ] The repo should be at least 30 days old.
- [ ] The documentation is in English.
- [ ] The project is active and maintained.
- [ ] The project accepts contributions.
- [ ] Not a commercial product.

### Apps/Websites

- [ ] The website is available without errors and load in a reasonable amount of time.
- [ ] The website is using Vite intensively.
- [ ] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.

### CODE REVIEW

**Review by antfu — CHANGES_REQUESTED** [review]
Please fix the lint error.

**Review by richajak — COMMENTED** [review]
fixed lint issue

**Review by antfu — CHANGES_REQUESTED** [review]
It's it been covered by the official preact template of `create-vite-app`?

**Comment by richajak** [comment]
I am aware of that. Actually this template is written specifically as simpler version of the official Preact Vite plugin launched recently (https://github.com/preactjs/preset-vite) I feel that the official plugin does not carry the spirit of simplicity in Preact by importing lots of dev dependency. It's unlike the WMR Preact tool that I am currently using, where it simply imports Preact, nothing else.

**Comment by richajak** [comment]
In this topic, I also contribute even simpler template to FRE (similar to preact) at 
https://github.com/yisar/fre/tree/master/docs  
https://github.com/richajak/vite-fre

**Review by Scrum — CHANGES_REQUESTED** [review]
## Checklist

- [ ] git: pull request template structure not broken
- [ ] git: pull request template not selected `type`
- [ ] git: pull request template not checked `Checklist`
- [ ] git: empty commit
- [ ] git: link not to repository
- [ ] git: link description contains a link to the author / third-party resource
- [ ] git: broken PR
- [x] git: no conflicts resolved
- [ ] git: doublicate
- [ ] time: not updated for more than 6 months
- [ ] category: not in its category
- [ ] lists: not the last on the list
- [ ] docs: no documentation
- [ ] docs: non-english documentation
- [ ] project: commercial product
- [ ] project: dead project
- [ ] project: does not accept donat
- [ ] site: no link to the site
- [ ] site: site with errors
- [ ] site: not actively using vuejs
- [ ] site: not original
> Follow the rules [CONTRIBUTING](https://github.com/vitejs/awesome-vite/blob/master/.github/contributing.md)

**Review by souzagab — APPROVED** [review]
🥇

**Pull request closed without merging**
