### PR TITLE
Add @brillout/vite-plugin-mdx

### PR DESCRIPTION
**Pull request by brillout**
Add ressource https://github.com/brillout/vite-plugin-mdx.

### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [x] Pull request template structure not broken

### `Type`

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Fix
- [x] Feature 

### `Checklist`

> ℹ️  Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md).

> 👉  _Put an `x` in the boxes that apply._

- [x] Title as described.
- [x] Make sure you put things in the right category!
- [x] Always add your items to the end of a list.
- [x] Your plugin/tool is working with Vite 2.0 and onward.

#### `Open Source`

- [x] Link description does not contain a link to an author / third-party resource
- [x] The documentation (README) contains a description of the project, illustration of the project with a demo or screenshots and a CONTRIBUTING section
- [x] The documentation is in English.
- [x] The project is active and maintained.
- [x] The project accepts contributions.
- [x] Not a commercial product

### CODE REVIEW

**Review by antfu — CHANGES_REQUESTED** [review]
Is Vue fully supported? (saw `WIP` on your README). If so, please provide more info about how to configure it to support MDX v1/v2 for React/Vue. Thanks.

**Comment by brillout** [comment]
Vue is not entirely working right now, but I'll finish the implementation when enough users upvote https://github.com/brillout/vite-plugin-mdx/issues/3.

> how to configure it to support MDX v1/v2

MDX is a peer dependency, so it can be used with any MDX version. This doesn't really need any explanation as the `Getting Started` section starts with:


1. Install `@brillout/vite-plugin-mdx` as well as MDX.
    ~~~sh
    npm install @brillout/vite-plugin-mdx
    npm install @mdx-js/mdx
    npm install @mdx-js/react
    ~~~

`vite-plugin-mdx` has already been used with v1 as well as v2.

**Comment by brillout** [comment]
I just added following note to the getting started, to make it clearer.

> You can install MDX v1 as well as MDX v2; @brillout/vite-plugin-mdx works with both.

**Comment by antfu** [comment]
So, can you move your plugin into the `React` section and remove the description about Vue? Thanks.

**Comment by brillout** [comment]
Done

**Comment by brillout** [comment]
I also improved the commit messages.

**Pull request merged**
