### PR TITLE
docs: Fix a broken link

### PR DESCRIPTION
**Pull request by jihchi**
The original link is broken (deprecated), update the link to correct one.

---
 
> Please make sure all the requirements are satisfied, otherwise the PR could be closed without further notice.

## Checklist

- [x] Title as described.
- [x] Make sure you put things in the right category.
- [x] The description of your item should be a sentence with less than 24 words.
- [x] Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
- [x] Always add your items to the end of a list.

### Plugins/Tools

N/A

### Starter Templates

N/A

### Apps/Websites

N/A

### CODE REVIEW

**Review by Scrum — APPROVED** [review]

**Comment by Scrum** [comment]
@jihchi https://github.com/vitejs/awesome-vite/pull/224/checks?check_run_id=3142357332

**Comment by jihchi** [comment]
> @jihchi https://github.com/vitejs/awesome-vite/pull/224/checks?check_run_id=3142357332

Fixed in commit d0d63573263931e3891f700a672ea9e3fc9bf4e0

Thanks @Scrum for the approval.

**Review by Scrum — APPROVED** [review]

**Comment by Scrum** [comment]
@jihchi resolve pls.

**Comment by jihchi** [comment]
> @jihchi resolve pls.

Done.

**Pull request merged**
