### PR TITLE
docs: vite-plugin-simple-json-server added

### PR DESCRIPTION
**Pull request by alextim**
### Plugins/Tools

vite-plugin-simple-json-server

### CODE REVIEW

**Comment by Scrum** [comment]
need resolve conflict

**Comment by Scrum** [comment]
Placing campaign banners in readmi seems not the best for this project. @antfu @patak-dev  Correct me if I'm wrong

**Comment by antfu** [comment]
I think it's the authors' freedom to do about their README. But for this one, I'd wait for a couple of weeks to see if there are real demand from the community.

**Comment by alextim** [comment]
> Placing campaign banners in readmi seems not the best for this project. @antfu @patak-dev Correct me if I'm wrong

This is not a "campaign banner" in the readme of my PERSONAL project. This is a civilizational choice based on universal values. 
Thanks for your time.

**Comment by Scrum** [comment]
> This is not a "campaign banner" in the readme of my PERSONAL project. This is a civilizational choice based on universal values. 
> 
> Thanks for your time.

let's immediately spread the points, I am against war and I am for the civilized world and readmi is yours and your project and you are free in everything, but the meaning of your package and the slogan in it are completely different.  What is your goal?  convey to people your position or your package?

**Pull request closed without merging**
