### PR TITLE
Add `vue3-typescript-tailwind-starter`

### PR DESCRIPTION
**Pull request by vincentdoerig**
- [x] Pull request template structure not broken

### `Type`

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Fix
- [x] Feature 

### `Checklist`

> ℹ️  Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md).

> 👉  _Put an `x` in the boxes that apply._

- [x] Title as described
- [x] Make sure you put things in the right category!
- [x] Always add your items to the end of a list

#### `Open Source`

- [x] Link description does not contain a link to an author / third-party resource
- [x] The documentation (README) contains a description of the project, illustration of the project with a demo or screenshots and a CONTRIBUTING section
- [x] The documentation is in English.
- [x] The project is active and maintained.
- [x] The project accepts contributions.
- [x] Not a commercial product

#### `Apps/Websites`

- [x] The website is available without errors or ssl certificate problems, and load in a reasonable amount of time.
- [x] The website is using Vite intensively.
- [x] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.
- [x] A commercial product using Vite, provided that guests could reasonably check out how Vite was used A commercial product using Vite, provided that guests could reasonably check out how Vite was used (i.e. A headless CMS which uses Vite for the Admin/editor Area and offers a free tier).

### CODE REVIEW

**Comment by antfu** [comment]
What's the difference between the existing ones?

**Comment by vincentdoerig** [comment]
Having ESLint. I haven't seen any other template use it. I also tried to create mine as simple as possible.

**Comment by antfu** [comment]
@vincentdoerig Well, we are already having quite a few templates on the list and I don't think adding ESLint is significant enough the be included as yet another one. Besides, ESLint does not relate that much to Vue nor Vite. Thanks for your contribution but sorry as I would close this for now. (P.S. [vitesse](https://github.com/antfu/vitesse) has ESLint tho)

**Comment by vincentdoerig** [comment]
Fair enough. Thanks!

**Comment by Jogai** [comment]
It seems a good template, and brings at least as much as others, so I'd say, why not? It seems to me more choice is always better. (especcially if vue is marketed as beginner-friendly)

**Pull request closed without merging**
