### PR TITLE
docs: add create-awesome-node-app

### PR DESCRIPTION
**Pull request by ulises-jeremias**
> Please make sure all the requirements are satisfied, otherwise the PR could be closed without further notice.

## Checklist

- [x] Title as described.
- [x] Make sure you put things in the right category.
- [x] The description of your item should be a sentence with less than 24 words.
- [x] Avoid using links and parentheses in description. 
- [x] Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
- [x] Use proper case for terms (e.g. `GitHub`, `TypeScript`, `ESLint`, etc.)
- [x] When mentioning tools, omit versions whenever possible (e.g. use `TypeScript` instead of `TypeScript 4.x`, but keep `Vue 2` and `Vue 3` as they're incompatible).
- [x] When mentioning package names, use quotes whenever possible.
- [x] Always add your items to the end of a list.

### Plugins/Tools

- [ ] The plugin/tool is working with **Vite 2.x and onward**.
- [ ] The project is Open Source.
- [ ] The project follows the [Vite Plugins Conventions](https://vitejs.dev/guide/api-plugin.html#conventions).
- [ ] The plugin uses Vite-specific hooks and can't be implemented as a [Compatible Rollup Plugin](https://vitejs.dev/guide/api-plugin.html#rollup-plugin-compatibility).
- [ ] The repo should be at least 30 days old.
- [ ] The documentation is in English.
- [ ] The project is active and maintained (inactive projects for longer 6 months will be removed without further notice).
- [ ] The project accepts contributions.
- [ ] Not a commercial product.

### Starter Templates

- [x] The starter template is working with **Vite 2.x and onward**.
- [x] The documentation is in English.
- [x] The starter template must provide enough instructions / documentation about how to start up and what's included.
- [x] A screenshot or a live demo should be included.
- [x] The repo should be at least 30 days old.
- [x] Should be differentiable from the existing starter templates. 

### Apps/Websites

- [ ] The website is available without errors and load in a reasonable amount of time.
- [ ] The website must be Open Source and showing it's using Vite intensively.
- [ ] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.

### CODE REVIEW

**Comment by Scrum** [comment]
From the description it is not clear the advantages over the rest.

**Comment by ulises-jeremias** [comment]
gotcha, I'll add a gif soon!

**Comment by ulises-jeremias** [comment]
@Scrum here there is a demonstration of the power of the tool. It provides multiple base templates using Vite (for react apps, web extensions, monorepos) and some others, along with multiple addons for each template (depending on the kind of application)

cna

it also allows us (maintainers and community) to add more templates and extensions in an easy way. We will start announcing it in some conferences this year 😊

**Comment by ulises-jeremias** [comment]
I just added the same gif as part of the documentation of the command 👌🏻

**Comment by ulises-jeremias** [comment]
I just updated to `Scaffolding your application choosing between different templates or create a modular setup from the tools/libraries in trend with TypeScript!`

**Comment by ulises-jeremias** [comment]
@Scrum let me know if you want me to do any other update to the description! 😊

**Comment by ulises-jeremias** [comment]
@Scrum any updates on this?

**Comment by Scrum** [comment]
@ulises-jeremias Could you shorten the description leaving only the gist?

**Comment by ulises-jeremias** [comment]
> @ulises-jeremias Could you shorten the description leaving only the gist?

@Scrum done!

**Review by Scrum — APPROVED** [review]

**Pull request merged**
