### PR TITLE
vue3-vite-tsx-element-plus-admin

### PR DESCRIPTION
**Pull request by klover2**
> Please make sure all the requirements are satisfied, otherwise the PR could be closed without further notice.

## Checklist

- [ ] Title as described.
- [ ] Make sure you put things in the right category.
- [ ] The description of your item should be a sentence with less than 24 words.
- [ ] Avoid using links and parentheses in description. 
- [ ] Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
- [ ] Use proper case for terms (e.g. `GitHub`, `TypeScript`, `ESLint`, etc.)
- [ ] When mentioning tools, omit versions whenever possible (e.g. use `TypeScript` instead of `TypeScript 4.x`, but keep `Vue 2` and `Vue 3` as they're incompatible).
- [ ] When mentioning package names, use quotes whenever possible.
- [x] Always add your items to the end of a list.

### Plugins/Tools

- [x] The plugin/tool is working with **Vite 2.x and onward**.
- [x] The project is Open Source.
- [x] The project follows the [Vite Plugins Conventions](https://vitejs.dev/guide/api-plugin.html#conventions).
- [ ] The plugin uses Vite-specific hooks and can't be implemented as a [Compatible Rollup Plugin](https://vitejs.dev/guide/api-plugin.html#rollup-plugin-compatibility).
- [ ] The repo should be at least 30 days old.
- [ ] The documentation is in English.
- [ ] The project is active and maintained (inactive projects for longer 6 months will be removed without further notice).
- [ ] The project accepts contributions.
- [x] Not a commercial product.

### Starter Templates

- [x] The starter template is working with **Vite 2.x and onward**.
- [ ] The documentation is in English.
- [x] The starter template most provide enough instructions / documentation about how to start up and what's is included.
- [ ] A screenshot or a live demo should be included.
- [ ] The repo should be at least 30 days old.
- [ ] Should be differentiable from the existing starter templates. 

### Apps/Websites

- [ ] The website is available without errors and load in a reasonable amount of time.
- [ ] The website must be Open Source and showing it's using Vite intensively.
- [ ] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.

### CODE REVIEW

**Comment by Jogai** [comment]
> (Continuously updated)

Is that a promise you can hold?

**Comment by klover2** [comment]
> > (Continuously updated)
> 
> Is that a promise you can hold?
Yes, I will use my spare time to maintain this open source project, because there is no complete information about vite+tsx to write the front end. I want to be the first person to contribute source code to make the front end more perfect.

**Comment by Jogai** [comment]
I appreciate the sentiment, but that's how most people start with an open source project. In practice its a lot harder to actually keep doing, especially when you

> use my spare time 

At least its a bold claim, which does not belong on the list. There are other projects that are well maintained, but they don't have that claim in this list either.

**Comment by klover2** [comment]
> I appreciate the sentiment, but that's how most people start with an open source project. In practice its a lot harder to actually keep doing, especially when you
> 
> > use my spare time
> 
> At least its a bold claim, which does not belong on the list. There are other projects that are well maintained, but they don't have that claim in this list either.

You can take a look at the projects that I have been maintaining before. I have been maintaining and answering users' questions.Because open source allows more people to use it, which makes me feel very happy and successful.
eg: 
https://github.com/klover2/wechatpay-node-v3-ts

**Comment by Jogai** [comment]
Hate to say this, but its not really proving anything. Its a few releases with almost every release needing a patch immediately.

**Pull request closed without merging**
