### PR TITLE
chore: add libraries  section and kendo

### PR DESCRIPTION
**Pull request by zdravkov**
### `General`

> ✏️ Mark the necessary items without changing the structure of the PR template.

- [x] Pull request template structure not broken

### `Type`

> ℹ️  What types of changes does your code introduce?

> 👉 _Put an `x` in the boxes that apply_

- [ ] Fix
- [x] Feature 

### `Checklist`

> ℹ️  Check all checkboxes - this will indicate that you have done everything in accordance with the rules in [CONTRIBUTING](https://github.com/vuejs/awesome-vue/blob/master/.github/contributing.md).

> 👉  _Put an `x` in the boxes that apply._

- [x] Title as described.
- [x] Make sure you put things in the right category!
- [x] Always add your items to the end of a list.
- [x] Your plugin/tool is working with Vite 2.0 and onward.

#### `Open Source`

- [ ] Link description does not contain a link to an author / third-party resource
- [ ] The documentation (README) contains a description of the project, illustration of the project with a demo or screenshots and a CONTRIBUTING section
- [ ] The documentation is in English.
- [ ] The project is active and maintained.
- [ ] The project accepts contributions.
- [ ] Not a commercial product

#### `Apps/Websites`

- [ ] The website is available without errors or ssl certificate problems, and load in a reasonable amount of time.
- [ ] The website is using Vite intensively.
- [ ] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.
- [ ] A commercial product using Vite, provided that guests could reasonably check out how Vite was used A commercial product using Vite, provided that guests could reasonably check out how Vite was used (i.e. A headless CMS which uses Vite for the Admin/editor Area and offers a free tier).

### CODE REVIEW

**Comment by antfu** [comment]
Still not sure, maybe try awesome-vue or [awesome-vue-3](https://github.com/blacksonic/awesome-vue-3)?

**Comment by zdravkov** [comment]
I will surely do - kendo is already there - but isn't it ok to have the libraries that support Vite listed somewhere here, too? If you have a better idea to position the message I will apply it.

**Comment by antfu** [comment]
I think this list should be related to Vite's ecosystem (plugin, dev-tools, etc). Since Vite it's a dev server and bundler, most of the libraries should be supported without even knowing it's Vite. You would not see something like an awesome-webpack list that contains all the libraries that compatible with webpack. It's great to know that Kendo works for Vue 3 and Vite but it's a bit too verbose to be listed here. Hope that makes my point clear. Thanks.

**Comment by zdravkov** [comment]
Yes, thank you for your time :)

**Pull request closed without merging**
