### PR TITLE
Vite plugin json server

### PR DESCRIPTION
**Pull request by yracnet**
> Please make sure all the requirements are satisfied, otherwise the PR could be closed without further notice.

## Checklist

- [X] Title as described.
- [X] Make sure you put things in the right category.
- [X] The description of your item should be a sentence with less than 24 words.
- [X] Avoid using links and parentheses in description. 
- [X] Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
- [ ] Use proper case for terms (e.g. `GitHub`, `TypeScript`, `ESLint`, etc.)
- [X] When mentioning tools, omit versions whenever possible (e.g. use `TypeScript` instead of `TypeScript 4.x`, but keep `Vue 2` and `Vue 3` as they're incompatible).
- [X] When mentioning package names, use quotes whenever possible.
- [X] Always add your items to the end of a list.

### Plugins/Tools

- [X] The project is Open Source.
- [X] The project follows the [Vite Plugins Conventions](https://vitejs.dev/guide/api-plugin.html#conventions).
- [X] The plugin uses Vite-specific hooks and can't be implemented as a [Compatible Rollup Plugin](https://vitejs.dev/guide/api-plugin.html#rollup-plugin-compatibility).
- [X] The repo should be at least 30 days old.
- [X] The documentation is in English.
- [X] The project is active and maintained (inactive projects for longer 6 months will be removed without further notice).
- [X] The project accepts contributions.
- [X] Not a commercial product.

### CODE REVIEW

**Comment by yracnet** [comment]
reorder

**Review by Scrum — CHANGES_REQUESTED** [review]
json-server -> JSON Server

**Comment by yracnet** [comment]
Applied

**Review by Scrum — APPROVED** [review]

**Comment by Scrum** [comment]
need resolve

**Comment by yracnet** [comment]
@Scrum applied

**Review by Scrum — APPROVED** [review]

**Pull request merged**
