### PR TITLE
add vite-tauri-template to vue 3 section

### PR DESCRIPTION
**Pull request by yooneskh**

### CODE REVIEW

**Review by Scrum — CHANGES_REQUESTED** [review]
## Checklist

- [x] git: pull request template structure not broken
- [x] git: pull request template not selected `type`
- [x] git: pull request template not checked `Checklist`
- [ ] git: empty commit
- [ ] git: link not to repository
- [ ] git: link description contains a link to the author / third-party resource
- [ ] git: broken PR
- [x] git: no conflicts resolved
- [ ] git: doublicate
- [ ] time: not updated for more than 6 months
- [ ] category: not in its category
- [ ] lists: not the last on the list
- [ ] docs: no documentation
- [ ] docs: non-english documentation
- [ ] project: commercial product
- [ ] project: dead project
- [ ] project: does not accept donat
- [ ] site: no link to the site
- [ ] site: site with errors
- [ ] site: not actively using vuejs
- [ ] site: not original
> Follow the rules [CONTRIBUTING](https://github.com/vitejs/awesome-vite/blob/master/.github/contributing.md)

**Comment by yooneskh** [comment]
i didn't get exactly what was the problem. I resolved the conflict though. Should i do anything else? @Scrum

**Comment by Scrum** [comment]
> i didn't get exactly what was the problem. I resolved the conflict though. Should i do anything else?

For further attachments, do not delete the PR template, mark the items described in it according to your attachment.

**Review by Scrum — CHANGES_REQUESTED** [review]
## Checklist

- [ ] git: pull request template structure not broken
- [ ] git: pull request template not selected `type`
- [ ] git: pull request template not checked `Checklist`
- [ ] git: empty commit
- [ ] git: link not to repository
- [ ] git: link description contains a link to the author / third-party resource
- [ ] git: broken PR
- [ ] git: no conflicts resolved
- [ ] git: doublicate
- [ ] time: not updated for more than 6 months
- [ ] category: not in its category
- [x] lists: not the last on the list
- [ ] docs: no documentation
- [ ] docs: non-english documentation
- [ ] project: commercial product
- [ ] project: dead project
- [ ] project: does not accept donat
- [ ] site: no link to the site
- [ ] site: site with errors
- [ ] site: not actively using vuejs
- [ ] site: not original
> Follow the rules [CONTRIBUTING](https://github.com/vitejs/awesome-vite/blob/master/.github/contributing.md)

**Comment by yooneskh** [comment]
Oh i see. I made the PR directly from VSCode and it did not show me any PR template. i will have that in mind for later on. @Scrum

**Comment by yooneskh** [comment]
I moved my edition to end of the list. @Scrum

**Review by Scrum — APPROVED** [review]

**Pull request merged**
