### PR TITLE
feat: add vite-vue-box

### PR DESCRIPTION
**Pull request by NelsonYong**
> Please make sure all the requirements are satisfied, otherwise the PR could be closed without further notice.

## Checklist

- [x] Title as described.
- [x] Make sure you put things in the right category.
- [x] The description of your item should be a sentence with less than 24 words.
- [x] Avoid using links and parentheses in description. 
- [x] Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
- [x] Use proper case for terms (e.g. `GitHub`, `TypeScript`, `ESLint`, etc.)
- [x] When mentioning tools, omit versions whenever possible (e.g. use `TypeScript` instead of `TypeScript 4.x`, but keep `Vue 2` and `Vue 3` as they're incompatible).
- [x] When mentioning package names, use quotes whenever possible.
- [x] Always add your items to the end of a list.

### Plugins/Tools

- [ ] The plugin/tool is working with **Vite 2.x and onward**.
- [x] The project is Open Source.
- [ ] The project follows the [Vite Plugins Conventions](https://vitejs.dev/guide/api-plugin.html#conventions).
- [ ] The plugin uses Vite-specific hooks and can't be implemented as a [Compatible Rollup Plugin](https://vitejs.dev/guide/api-plugin.html#rollup-plugin-compatibility).
- [ ] The repo should be at least 30 days old.
- [x] The documentation is in English.
- [ ] The project is active and maintained (inactive projects for longer 6 months will be removed without further notice).
- [ ] The project accepts contributions.
- [x] Not a commercial product.

### Starter Templates

- [ ] The starter template is working with **Vite 2.x and onward**.
- [ ] The documentation is in English.
- [ ] The starter template most provide enough instructions / documentation about how to start up and what's is included.
- [ ] A screenshot or a live demo should be included.
- [ ] The repo should be at least 30 days old.
- [ ] Should be differentiable from the existing starter templates. 

### Apps/Websites

- [ ] The website is available without errors and load in a reasonable amount of time.
- [ ] The website must be Open Source and showing it's using Vite intensively.
- [ ] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.

### CODE REVIEW

**Comment by Jogai** [comment]
> farewell to the vueuse,The vue-hooks-plus can satisfy most of your business

Why talk negative about a similar, and also outstanding, project?

**Comment by NelsonYong** [comment]
> > farewell to the vueuse,The vue-hooks-plus can satisfy most of your business
> 
> Why talk negative about a similar, and also outstanding, project?

Sorry for my words being radical, I need a tool function that easily satisfies a lot of business and can be used quickly. I did the research and people use vueuse with very few core features. I have deleted the related words.

**Review by Scrum — APPROVED** [review]

**Comment by Jogai** [comment]
> I did the research and people use vueuse with very few core features.

What do you exactly mean by that? Because in almost every aspect vueuse looks like the more mature one: https://npmtrends.com/@vueuse/core-vs-vue-hooks-plus

> I have deleted the related words.

Thanks for that.

Not saying your work is not awesome, but if you just want to get people to use your library its fine to say "Including my vue hooks package providing some nice utilities".

**Comment by NelsonYong** [comment]
> > I did the research and people use vueuse with very few core features.
> 
> What do you exactly mean by that? Because in almost every aspect vueuse looks like the more mature one: https://npmtrends.com/@vueuse/core-vs-vue-hooks-plus
> 
> > I have deleted the related words.
> 
> Thanks for that.
> 
> Not saying your work is not awesome, but if you just want to get people to use your library its fine to say "Including my vue hooks package providing some nice utilities".

Thank you very much for your comments. vueuse is great, but I think it is in a weak business, such as the request, and it can't be handled well. I corrected my previous view. I think you can use it if you think it's good. What do you think?

**Pull request merged**
