### PR TITLE
Add vite-preset-react

### PR DESCRIPTION
**Pull request by PuruVJ**
> Please make sure all the requirements are satisfied, otherwise the PR could be closed without further notice.

## Checklist

- [x] Title as described.
- [x] Make sure you put things in the right category.
- [x] The description of your item should be a sentence with less than 24 words.
- [x] Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
- [ ] Always add your items to the end of a list.

### Plugins/Tools

- [x] The plugin/tool is working with **Vite 2.0 and onward**.
- [x] The project is Open Source.
- [x] The project follows the [Vite Plugins Conventions](https://vitejs.dev/guide/api-plugin.html#conventions).
- [ ] The repo should be at least 30 days old.
- [x] The documentation is in English.
- [x] The project is active and maintained.
- [x] The project accepts contributions.
- [x] Not a commercial product.

### CODE REVIEW

**Comment by PuruVJ** [comment]
@antfu What do you think of this new `General` category? Is it Ok? Should I try something else?

**Comment by antfu** [comment]
Maybe `Presets` - and the link is 404

**Comment by PuruVJ** [comment]
Fixed it 😅

**Comment by PuruVJ** [comment]
@antfu is it ok now?

**Comment by PuruVJ** [comment]
Hi, Its been 3 days. Is there anything not right with this package that prohibits it from being merged into the repo? If so, I'll gladly close the PR.

Or I can wait if you're having a busy time, I understand.

**Comment by antfu** [comment]
Just doing this in batches, be a bit more patient, thanks

**Comment by PuruVJ** [comment]
No problem!!! take all the time you need 👍👍

**Pull request merged**
