### PR TITLE
Add two Solid plugins

### PR DESCRIPTION
**Pull request by nathanbabcock**
- [`vite-plugin-solid-markdown`](https://github.com/xbmlz/vite-plugin-solid-markdown) was already listed, but miscategorized under the "framework-agnostic plugins" section
- [`vite-plugin-solid-svg`](https://github.com/jfgodoy/vite-plugin-solid-svg) is new ✨ 

Both added underneath the SolidJS plugins section.

---

## Checklist

- [X] Title as described.
- [X] Make sure you put things in the right category.
- [X] The description of your item should be a sentence with less than 24 words.
- [X] Avoid using links and parentheses in description. 
- [X] Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
- [X] Use proper case for terms (e.g. `GitHub`, `TypeScript`, `ESLint`, etc.)
- [X] When mentioning tools, omit versions whenever possible (e.g. use `TypeScript` instead of `TypeScript 4.x`, but keep `Vue 2` and `Vue 3` as they're incompatible).
- [X] When mentioning package names, use quotes whenever possible.
- [X] Always add your items to the end of a list.

### Plugins/Tools

- [X] The plugin/tool is working with **Vite 2.x and onward**.
- [X] The project is Open Source.
- [X] The project follows the [Vite Plugins Conventions](https://vitejs.dev/guide/api-plugin.html#conventions).
- [X] The plugin uses Vite-specific hooks and can't be implemented as a [Compatible Rollup Plugin](https://vitejs.dev/guide/api-plugin.html#rollup-plugin-compatibility).
- [X] The repo should be at least 30 days old.
- [X] The documentation is in English.
- [X] The project is active and maintained (inactive projects for longer 6 months will be removed without further notice).
- [X] The project accepts contributions.
- [X] Not a commercial product.

### CODE REVIEW

**Review by Scrum — CHANGES_REQUESTED** [review]
## Checklist

- [ ] git: pull request template structure not broken
- [ ] git: pull request template not selected `type`
- [ ] git: pull request template not checked `Checklist`
- [ ] git: empty commit
- [ ] git: link not to repository
- [ ] git: link description contains a link to the author / third-party resource
- [x] git: link description no `for Vite` or `Vite plugin`
- [ ] git: link description no `Fast` or `Super-fast` etc
- [ ] git: link description short description short description (one sentence in 24 words, no expanded explanation)
- [ ] git: terms in the wrong formats (e.g. Typescript over TypeScript)
- [ ] git: broken PR
- [ ] git: no conflicts resolved
- [ ] git: doublicate
- [ ] time: not updated for more than 6 months
- [ ] category: not in its category
- [ ] lists: not the last on the list
- [ ] docs: no documentation
- [ ] docs: non-english documentation
- [ ] project: commercial product
- [ ] project: dead project
- [ ] project: does not accept donat
- [ ] site: no link to the site
- [ ] site: site with errors
- [ ] site: not actively using vuejs
- [ ] site: not original
> Follow the rules [CONTRIBUTING](https://github.com/vitejs/awesome-vite/blob/master/.github/contributing.md)

**Comment by nathanbabcock** [comment]
Fixed

**Comment by Scrum** [comment]
https://github.com/vitejs/awesome-vite/actions/runs/4405185901/jobs/7715765363

**Comment by nathanbabcock** [comment]
Cheers @Scrum 🍺

**Pull request merged**
