### PR TITLE
Add "view-launcher"

### PR DESCRIPTION
**Pull request by yaquawa**
Added [view-launcher](https://github.com/view-launcher/view-launcher)

## Checklist

- [x] Title as described.
- [x] Make sure you put things in the right category.
- [x] The description of your item should be a sentence with less than 24 words.
- [x] Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
- [x] Always add your items to the end of a list.

### Plugins/Tools

- [x] The plugin/tool is working with **Vite 2.0 and onward**.
- [x] The project is Open Source.
- [x] The project follows the [Vite Plugins Conventions](https://vitejs.dev/guide/api-plugin.html#conventions).
- [x] The repo should be at least 30 days old.
- [x] The documentation is in English.
- [x] The project is active and maintained.
- [x] The project accepts contributions.
- [x] Not a commercial product.

### CODE REVIEW

**Review by antfu — CHANGES_REQUESTED** [review]
Can you explain how this relates to Vite?

**Comment by yaquawa** [comment]
Hi @antfu , thanks for the reviewing!

I've been using your fantastic `vite-plugin-windicss` for a while. Thanks for that too!
To put it simple, just like yours, this is nothing but a dev tool that work with Vite.
That's it!

At the current stage, it works both in rollup and Vite, so according to the [conventions](https://vitejs.dev/guide/api-plugin.html#conventions) I name it as [@view-launcher/rollup-plugin](https://github.com/view-launcher/vue-view-launcher/tree/master/packages/rollup-plugin).


As an aside, actually the original motivation I created this tool is to improve the maintenance costs of ***Tailwind.css***.
For example whenever you want to modify the style, the good old way is searching the class name through all the component files, or if you have good memory, you may rely on your memory to find the location of the component, then edit the class name right? That's where the maintenance costs are incurred.

But I found it is also the solution for this situation: whenever you want to modify the view, chances are you are keep asking "***Where is the code of this piece of UI ?***", especially when you are stared to work with a new team.

Well I think this is a good idea to share to people, but if you don't think this something that is "awesome" it shouldn't be a part of "awesome-vite", feel free to reject or approve😁

**Comment by antfu** [comment]
From the demo, it looks quite promising, awesome work!

While I'd like to include it in the list, there is no clear sign it relates to Vite.

I'd suggest you show some installation guides and even better an example/demo of how to get started with Vite in your README. Let me know when you finished that and make the project solid. Looking forward to that.

**Comment by yaquawa** [comment]
@antfu Thanks for the suggestion! 
Yes you're right, I'm going to add more information to the README later-on!

**Comment by yaquawa** [comment]
@antfu  
I've updated the README for both [view-launcher/vue-view-launcher](https://github.com/view-launcher/vue-view-launcher/tree/master/packages/rollup-plugin#example-for-vite) and [view-launcher/view-launcher](https://github.com/view-launcher/view-launcher), let me know if this is clear enough for you, thanks 🙇🏻‍♂️

**Comment by Jogai** [comment]
It sure is awesome!

**Review by Scrum — APPROVED** [review]

**Pull request merged**
