### PR TITLE
docs: add vue-pure-admin

### PR DESCRIPTION
**Pull request by xiaoxian521**
> Please make sure all the requirements are satisfied, otherwise the PR could be closed without further notice.

## Checklist

- [x] Title as described.
- [x] Make sure you put things in the right category.
- [x] The description of your item should be a sentence with less than 24 words.
- [x] Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
- [x] Always add your items to the end of a list.

### Plugins/Tools

- [x] The plugin/tool is working with **Vite 2.0 and onward**.
- [x] The project is Open Source.
- [x] The project follows the [Vite Plugins Conventions](https://vitejs.dev/guide/api-plugin.html#conventions).
- [x] The repo should be at least 30 days old.
- [x] The documentation is in English.
- [x] The project is active and maintained.
- [x] The project accepts contributions.
- [x] Not a commercial product.

### Starter Templates

- [x] The starter template is working with **Vite 2.0 and onward**.
- [x] The documentation is in English.
- [x] The starter template most provide enough instructions / documentation about how to start up and what's is included.
- [x] A screenshot or a live demo should be included.
- [x] The repo should be at least 30 days old.
- [x] Should be differentiable from the existing starter templates. 

### Apps/Websites

- [x] The website is available without errors and load in a reasonable amount of time.
- [x] The website must be Open Source and showing it's using Vite intensively.
- [x] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.

### CODE REVIEW

**Comment by Jogai** [comment]
Legacy is for vite 1 stuff I believe, you have to add it to only one readme

**Comment by xiaoxian521** [comment]
@Jogai 
> Legacy is for vite 1 stuff I believe, you have to add it to only one readme
hi, My project uses the latest vite version，What do you mean?

**Comment by Jogai** [comment]
Dont add it to README.legacy.md, it says: "We no longer accept new entries to this list"

**Comment by xiaoxian521** [comment]
@Jogai 
> Dont add it to README.legacy.md, it says: "We no longer accept new entries to this list"
Deleted

**Pull request merged**
