### PR TITLE
docs: add `ionic` & `capacitor` vue3+vite starter

### PR DESCRIPTION
**Pull request by reslear**

### CODE REVIEW

**Comment by Scrum** [comment]
https://github.com/vitejs/awesome-vite/actions/runs/3215133653/jobs/5434162984

**Comment by reslear** [comment]
hi @Scrum fixed, thx!

**Comment by Scrum** [comment]
https://github.com/vitejs/awesome-vite/actions/runs/3296195109/jobs/5483725880 and not the last on the list

**Comment by reslear** [comment]
hi @Scrum check again please :)

**Comment by Jogai** [comment]
lgtm

**Comment by Scrum** [comment]
https://github.com/vitejs/awesome-vite/actions/runs/3319489276/jobs/5799796994

**Comment by reslear** [comment]
@Scrum done thx ❤️)

**Comment by Scrum** [comment]
https://github.com/vitejs/awesome-vite/actions/runs/3624883532/jobs/6210218015

**Comment by reslear** [comment]
@Scrum done, check please)

**Review by Scrum — CHANGES_REQUESTED** [review]
## Checklist

- [ ] git: pull request template structure not broken
- [ ] git: pull request template not selected `type`
- [ ] git: pull request template not checked `Checklist`
- [ ] git: empty commit
- [ ] git: link not to repository
- [ ] git: link description contains a link to the author / third-party resource
- [ ] git: link description no `for Vite` or `Vite plugin`
- [ ] git: link description no `Fast` or `Super-fast` etc
- [ ] git: link description short description short description (one sentence in 24 words, no expanded explanation)
- [ ] git: terms in the wrong formats (e.g. Typescript over TypeScript)
- [ ] git: broken PR
- [ ] git: no conflicts resolved
- [ ] git: doublicate
- [ ] time: not updated for more than 6 months
- [ ] category: not in its category
- [x] lists: not the last on the list
- [ ] docs: no documentation
- [ ] docs: non-english documentation
- [ ] project: commercial product
- [ ] project: dead project
- [ ] project: does not accept donat
- [ ] site: no link to the site
- [ ] site: site with errors
- [ ] site: not actively using vuejs
- [ ] site: not original
> Follow the rules [CONTRIBUTING](https://github.com/vitejs/awesome-vite/blob/master/.github/contributing.md)

**Review by reslear — COMMENTED** [review]
moved

**Comment by reslear** [comment]
@Scrum done, check please)

**Review by Scrum — APPROVED** [review]

**Pull request merged**
