### PR TITLE
List vite-plugin-svelte, @vitejs/plugin-legacy, and @vitejs/plugin-vue-jsx

### PR DESCRIPTION
**Pull request by benmccann**
I didn't add the items to the end of lists because I thought that `@vitejs` plugins should be listed first as they're more official. I can update if desired

> Please make sure all the requirements are satisfied, otherwise the PR could be closed without further notice.

## Checklist

- [X] Title as described.
- [X] Make sure you put things in the right category.
- [X] The description of your item should be a sentence with less than 24 words.
- [X] Avoid using links and parentheses in description. 
- [X] Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
- [X] Use proper case for terms (e.g. `GitHub`, `TypeScript`, `ESLint`, etc.)
- [X] When mentioning tools, omit versions whenever possible (e.g. use `TypeScript` instead of `TypeScript 4.x`, but keep `Vue 2` and `Vue 3` as they're incompatible).
- [X] When mentioning package names, use quotes whenever possible.
- [ ] Always add your items to the end of a list.

### Plugins/Tools

- [X] The plugin/tool is working with **Vite 2.x and onward**.
- [X] The project is Open Source.
- [X] The project follows the [Vite Plugins Conventions](https://vitejs.dev/guide/api-plugin.html#conventions).
- [X] The plugin uses Vite-specific hooks and can't be implemented as a [Compatible Rollup Plugin](https://vitejs.dev/guide/api-plugin.html#rollup-plugin-compatibility).
- [X] The repo should be at least 30 days old.
- [X] The documentation is in English.
- [X] The project is active and maintained (inactive projects for longer 6 months will be removed without further notice).
- [X] The project accepts contributions.
- [X] Not a commercial product.

### Starter Templates

- [ ] The starter template is working with **Vite 2.x and onward**.
- [ ] The documentation is in English.
- [ ] The starter template most provide enough instructions / documentation about how to start up and what's is included.
- [ ] A screenshot or a live demo should be included.
- [ ] The repo should be at least 30 days old.
- [ ] Should be differentiable from the existing starter templates. 

### Apps/Websites

- [ ] The website is available without errors and load in a reasonable amount of time.
- [ ] The website must be Open Source and showing it's using Vite intensively.
- [ ] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.

### CODE REVIEW

**Review by Scrum — CHANGES_REQUESTED** [review]
## Checklist

- [ ] git: pull request template structure not broken
- [ ] git: pull request template not selected `type`
- [ ] git: pull request template not checked `Checklist`
- [ ] git: empty commit
- [ ] git: link not to repository
- [ ] git: link description contains a link to the author / third-party resource
- [x] git: link description no `for Vite` or `Vite plugin`
- [ ] git: link description no `Fast` or `Super-fast` etc
- [ ] git: link description short description short description (one sentence in 24 words, no expanded explanation)
- [ ] git: terms in the wrong formats (e.g. Typescript over TypeScript)
- [ ] git: broken PR
- [ ] git: no conflicts resolved
- [ ] git: doublicate
- [ ] time: not updated for more than 6 months
- [ ] category: not in its category
- [x] lists: not the last on the list
- [ ] docs: no documentation
- [ ] docs: non-english documentation
- [ ] project: commercial product
- [ ] project: dead project
- [ ] project: does not accept donat
- [ ] site: no link to the site
- [ ] site: site with errors
- [ ] site: not actively using vuejs
- [ ] site: not original
> Follow the rules [CONTRIBUTING](https://github.com/vitejs/awesome-vite/blob/master/.github/contributing.md)

**Comment by benmccann** [comment]
> link description no for Vite or Vite plugin

oops, I missed that one. updated!

> not the last on the list

one other thing I wanted to point out is the way I've done it now sorts it by version first so that we have all the v3 plugins first followed by v3 plugins, which I think is easier to consume. if you'd still like me to reorder them to put the newest one last and intermix versions I'm happy to do that

**Comment by Scrum** [comment]
https://github.com/vitejs/awesome-vite/blob/master/.github/contributing.md

**Comment by patak-js** [comment]
@Scrum your call here, but having the official Vite plugins first sounds ok in this context to guide people towards them first

**Comment by Scrum** [comment]
> @Scrum your call here, but having the official Vite plugins first sounds ok in this context to guide people towards them first

I'm in disarray because the rules are common to all, if we make exceptions, then we lose order.

> Always add your items to the end of a list. To be fair, the order is first-come-first-serve.

I propose to do justice based on the opinion of a third party @antfu ?

**Review by antfu — APPROVED** [review]
I think it's reasonable here

**Review by Scrum — APPROVED** [review]

**Pull request merged**
