### PR TITLE
feat: add vite-plugin-ts-nameof

### PR DESCRIPTION
**Pull request by Shinigami92**
### Checklist

- [x] Title as described.
- [x] Make sure you put things in the right category.
- [ ] The description of your item should be a sentence with less than 24 words.  
      _It's currently 47_.
- [x] Omit unnecessary words already provided in the context (e.g. `for Vite`, `a Vite plugin`).
- [x] Always add your items to the end of a list.

### Plugins/Tools

- [x] The plugin/tool is working with **Vite 2.0 and onward**.
- [x] The project is Open Source.
- [x] The project follows the [Vite Plugins Conventions](https://vitejs.dev/guide/api-plugin.html#conventions).
- [ ] The repo should be at least 30 days old.  
      _Released on `27. Feb. 2021`_.
- [x] The documentation is in English.
- [x] The project is active and maintained.
- [x] The project accepts contributions.
- [x] Not a commercial product.

### Apps/Websites

_No website or app_

- [ ] The website is available without errors and load in a reasonable amount of time.
- [ ] The website is using Vite intensively.
- [ ] The website is original and not too simple. For that reason, blogs and simple landing pages are rejected.

### CODE REVIEW

**Comment by antfu** [comment]
That's cool! I would recommend naming it to `vite-plugin-nameof`

**Comment by Shinigami92** [comment]
I didn't named it `vite-plugin-ts-nameof` and already released it :thinking:  
Should I really rename it and make a new release and mark the old one as deprecated?

@antfu Also which name would be better?

1. `vite-plugin-nameof`
2. `vite-plugin-ts-nameof`

Originally coming from https://github.com/dsherret/ts-nameof

**Comment by antfu** [comment]
> Should I really rename it and make a new release and mark the old one as deprecated?

Yeah, I think that's a good idea to do.

**Comment by Shinigami92** [comment]
Okay, so I think it's better to use `vite-plugin-ts-nameof`, because that's the real project name of the used underlying package

How should I name the `name` field?

https://github.com/Shinigami92/vite-plugin-ts-nameof/blob/854f4c3f702c784ac31179955fcb16dc434dd74b/src/index.ts#L5

Is there any convention? I originally copied `vite-tsconfig-paths` and used it as a template.

**Comment by Shinigami92** [comment]
@antfu Everything successfully renamed to `vite-plugin-ts-nameof` :tada:

**Comment by antfu** [comment]
> How should I name the name field?

It's better to just use your package name, `vite:` is more like an internal prefix for built-in plugins of Vite.

**Comment by antfu** [comment]
Looks good to me, I will merge it now :)

**Comment by Shinigami92** [comment]
Thank you 💚
Have a nice day :wave:

**Pull request merged**
