### PR TITLE
chore: fix lint and pin dependencies

### PR DESCRIPTION
**Pull request by brillout**
I didn't test my changes to the GitHub action but AFAICT it should work.

### CODE REVIEW

**Comment by antfu** [comment]
Do we have any problem with the previous approach? Thank you for the PR, but I actually keep it lock-free on purpose, as the only thing we care about is the markdown file and the dependencies are just cli tools which I don't think we need to keep that strict.

**Comment by brillout** [comment]
I removed the `package-lock.json`. Yes, the `lint` script wasn't working and this fixes it. Feel free to reject my PR, I don't mind.

**Comment by antfu** [comment]
Alright, I am taking it. Thank you.

**Comment by antfu** [comment]
I review them in batches, please wait for a bit longer.

**Pull request merged**
